baseURL: "https://panosni.github.io" 
title: Panayiotis Nicolaides
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Resume
          url: nicolaides_cv.pdf
          weight: 3 

params:
    description: "I am Director of Research at the EU Tax Observatory, Paris School of Economics. I specialise on the economics of taxation.
Previously, I worked as economic advisor to finance ministers during the Greek economic crisis and, as economist at the European Commission (DG TAXUD and Task Force for Greece)"
    author: Panayiotis Nicolaides
    googleAnalyticsID: "G-QMTGMPMS4L"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","talks","social intitiaves","resume"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Panayiotis Nicolaides
          subtitle: "I am the Director of Research at the [EU Tax Observatory,](https://www.taxobservatory.eu) [Paris School of Economics.](https://www.parisschoolofeconomics.eu) 
          I specialise on the economics of taxation, working on both policy and research. <br> <br>
          Previously, I worked at the European Commission and, as special economic advisor to finance ministers during the Greek economic crisis. From 2016 to 2019, I served as
          Alternate Member to the Eurogroup Working Group and as Alternate Director at European Stability Mechanism's Board of Directors. <br>"
          imageUrl: "picture.jpg"
          imageWidth: 310
          imageHeight: 425
          imageTitle: Panayiotis Nicolaides
          buttons:
            - name: Publications
              url: papers/
            - name: Talks
              url: talks/
            - name: Resume
              url: nicolaides_cv.pdf
    socialIcons:
            - name: Email
              url: mailto:pan.nicolaides@gmail.com
            - name: Google Scholar
              url: https://scholar.google.com/citations?user=ZNxFqicAAAAJ&hl=en
            - name: GitHub
              url: https://github.com/panosni
            - name: ORCID
              url: https://orcid.org/0000-0003-2289-428X
            - name: LinkedIn
              url: https://linkedin.com/in/panayiotis-nicolaides-07342242 
            - name: X
              url: https://x.com/pnicolaides
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Panayiotis Nicolaides"
      icon: favicon.ico
      iconHeight: 30

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2